ORG 100H
INCLUDE 'EMU8086.INC'

; PROMT THE USER TO ENTER A NUMBER
PRINT 'ENTER A NUMBER: $'

; SCAN THE NUMBER INPUT BY THE USER INTO CX 
; AND MOV IT INTO CX
CALL SCAN_NUM  
MOV AX,CX
XOR CX,CX

PRINTN
;PRINT 'YOUR INPUT IS: $'    
;CALL PRINT_NUM_UNS    
;PRINTN 

; PROMT THE USER TO ENTER A DIVISOR 
PRINT 'ENTER A DIVISOR: $'
CALL SCAN_NUM
PRINTN

; PERFORM DIVISION (AX / CX)
XOR DX, DX     ; CLEAR DX TO AVOID DIVISION ERRORS
DIV CX         ; DIVIDE AX BY CX

; PRINT THE RESULT
PRINT 'RESULT: $'
CALL PRINT_NUM_UNS   
PRINTN


PRINT 'THANKS FOR RUN THIS CODE...$'
DEFINE_SCAN_NUM      
DEFINE_PRINT_NUM_UNS
END
